cc_test(name = "test_compiler", 
        srcs = ["test_compiler.cpp", "test_virtual_machine.cpp", "main.cpp"],
        deps = ["@googletest//:gtest_main", "@googletest//:gtest", "//src:lox_compiler"]
)